### ISSUE TITLE
Need help, Please

### ISSUE THREAD

**Issue by Jutamad08** [256dpi/max-mqtt#3]
Hello, I've download your max-mqtt patched to send data. 
<img width="815" alt="Screen Shot 2563-10-17 at 18 01 08" src="https://user-images.githubusercontent.com/73021438/96335437-c45b5b80-10a2-11eb-9f51-3e7d28c461ff.png">

Then the message that I receive was come as a message (ex. /topic "0.02397" 0 0))

<img width="929" alt="Screen Shot 2563-10-17 at 17 22 58" src="https://user-images.githubusercontent.com/73021438/96335412-a4c43300-10a2-11eb-9373-44a8560a82b5.png">

And I need to use the value 0.02397. to adjust delay in my max patched.

Is there any suggestion to change message "0.02397"   to value.
Thank you

**Comment by 256dpi** [comment]
I guess "zl.nth" assumes 1 to be the first index of the list while "zl.mth" assumes 0 to be the first index. So either you need to use "zl.nth 1" or "zl.mth" to get the first value from a list. However, I usually use "unpack" to break the list up. 

<img width="310" alt="Screen Shot 2020-10-18 at 10 56 56" src="https://user-images.githubusercontent.com/696886/96362860-c79d2880-1130-11eb-99fe-ccd92595b66a.png">

**Comment by Jutamad08** [comment]
Thank you so much!!!
