### ISSUE TITLE
Windows version ? retain message, last will and qos support ?

### ISSUE THREAD

**Issue by siteswapjuggler** [256dpi/max-mqtt#4]
Hello, 

I'm very interested by using your object in one of my project. But I would like to know more about it or about the way to help you improving it. Does it support advanced mqtt features like last will, retain message and qos ? 

Also do you plan to release a windows version ?

Sincerely

**Comment by 256dpi** [comment]
It supports retained messages and QOS already, and there is also a build in the .zip for windows. However, the help patcher does not show all features. You can look at the source here https://github.com/256dpi/max-mqtt/blob/master/main.go to get more details. I should be relatively straight forward to add a "last-will" command to set a last will message. I'm always happy to receive contributions!
