### ISSUE TITLE
mqtt: could not load due to incorrect architecture 

### ISSUE THREAD

**Issue by angelescu-humain** [256dpi/max-mqtt#7]
Hey, I am trying to run the module in macOS Monterey 12.0.1 and get this error. Have I missed sth? 

![Bildschirmfoto 2021-10-29 um 14 37 45](https://user-images.githubusercontent.com/51321523/139435891-50972954-e52c-4867-9bda-a310c9a7e293.png)

**Comment by 256dpi** [comment]
I guess you're using a new M1 based Mac with a native version of Max, but the external is compiled for Intel.

**Comment by baklaci-humain** [comment]
@256dpi Thank you for your nice work. I am new to this but worth a shot:
Would it be possible to compile for M1; based on [this article](https://dev.to/tidalmigrations/how-to-cross-compile-go-app-for-apple-silicon-m1-27l6)?
I can imagine making an overload of [this function](https://github.com/256dpi/max-go/blob/9390d55cad00c906176ad75a4ed9c708818d8e70/cmd/maxgo/main.go#L109-L117) with the appropriate flags:
```
run("go",
	[]string{"build", "-v", "-buildmode=c-shared", "-o", filepath.Join("out", *name)},
	[]string{"CGO_ENABLED=1", "OOS=darwin", "GOARCH=arm64"},
	)
```

**Comment by 256dpi** [comment]
I just made a new release with the external compiled as a universal binary for both Intel and Apple Silicon platforms.
